// Auto-generated by tools/gen_pet.py -- do not edit by hand.
#ifndef PET_SPRITES_H
#define PET_SPRITES_H

#include "lvgl.h"

#define PET_FORM_W 48
#define PET_FORM_H 48
#define PET_ACC_W 16
#define PET_ACC_H 16
#define PET_FORM_COUNT 6
#define PET_TRAIT_COUNT 5

// Evolution is driven ONLY by the number of discovered places.
// Forms never regress: no death, no decay, no daily care.
enum {
    PET_FORM_SEED = 0, // >= 0 places
    PET_FORM_SPROUT = 1, // >= 2 places
    PET_FORM_YOUNG = 2, // >= 4 places
    PET_FORM_BUBU = 3, // >= 8 places
    PET_FORM_TRAVELER = 4, // >= 12 places
    PET_FORM_WORLD = 5, // >= 16 places
};

// Personality accessories composite on top of a form.
enum {
    PET_TRAIT_HOMEBODY = 0,
    PET_TRAIT_ROVER = 1,
    PET_TRAIT_SOCIAL = 2,
    PET_TRAIT_SOLO = 3,
    PET_TRAIT_ARENA = 4,
};

typedef struct {
    int16_t x;
    int16_t y;
} pet_anchor_t;

extern const lv_image_dsc_t pet_form_seed;
extern const lv_image_dsc_t pet_form_sprout;
extern const lv_image_dsc_t pet_form_young;
extern const lv_image_dsc_t pet_form_bubu;
extern const lv_image_dsc_t pet_form_traveler;
extern const lv_image_dsc_t pet_form_world;
extern const lv_image_dsc_t pet_acc_pillow;
extern const lv_image_dsc_t pet_acc_dust;
extern const lv_image_dsc_t pet_acc_hearts;
extern const lv_image_dsc_t pet_acc_quiet;
extern const lv_image_dsc_t pet_acc_glowstick;

extern const lv_image_dsc_t *const pet_form_sprites[PET_FORM_COUNT];
extern const lv_image_dsc_t *const pet_acc_sprites[PET_TRAIT_COUNT];
extern const pet_anchor_t pet_form_anchors[PET_FORM_COUNT];
extern const uint8_t pet_form_threshold[PET_FORM_COUNT];

// Returns the form index for a given place count. Pure function, testable
// without hardware. Callers MUST clamp so a stored form never decreases.
uint8_t pet_form_for_places(uint8_t places);

#endif // PET_SPRITES_H
