// Auto-generated by tools/gen_icons.py -- do not edit by hand.
#ifndef TRIBE_ICONS_MAYDAY_H
#define TRIBE_ICONS_MAYDAY_H

#include "lvgl.h"

#define TRIBE_ICON_W 32
#define TRIBE_ICON_H 32
#define TRIBE_ICON_COUNT 8

// Icon indices travel inside the BLE advert payload (3 bits, 0..7).
// Index 7 is a MOOD signal, not an identity -- callers must route it
// to the quiet feedback branch instead of the encounter animation.
enum {
    TRIBE_ICON_CARROT = 0,
    TRIBE_ICON_RABBIT = 1,
    TRIBE_ICON_BALL_PINK = 2,
    TRIBE_ICON_BALL_RED = 3,
    TRIBE_ICON_BALL_GREEN = 4,
    TRIBE_ICON_BALL_BLUE = 5,
    TRIBE_ICON_BALL_YELLOW = 6,
    TRIBE_ICON_NINEBALL = 7,
};

extern const lv_image_dsc_t tribe_icon_carrot;
extern const lv_image_dsc_t tribe_icon_rabbit;
extern const lv_image_dsc_t tribe_icon_ball_pink;
extern const lv_image_dsc_t tribe_icon_ball_red;
extern const lv_image_dsc_t tribe_icon_ball_green;
extern const lv_image_dsc_t tribe_icon_ball_blue;
extern const lv_image_dsc_t tribe_icon_ball_yellow;
extern const lv_image_dsc_t tribe_icon_nineball;

extern const lv_image_dsc_t *const tribe_icon_pack_mayday[TRIBE_ICON_COUNT];

#endif // TRIBE_ICONS_MAYDAY_H
