// AUTO-GENERATED by tools/gen_answer_data.js from main/answers.json. Do not edit.
#pragma once

#define ANSWER_DECK_COUNT 3
#define ANSWERS_PER_DECK 16

static const char * const ANSWER_DECK_NAMES[ANSWER_DECK_COUNT] = {
    "经典",
    "打工人",
    "程序员"
};

static const char * const ANSWERS[ANSWER_DECK_COUNT][ANSWERS_PER_DECK] = {
    {
        "是的，毫无疑问",
        "时机未到，再等等",
        "大胆去做吧",
        "答案就在你心中",
        "不要强求",
        "会有惊喜发生",
        "三思而后行",
        "现在就是最好时机",
        "听从你的直觉",
        "结果比想象中好",
        "换个角度看看",
        "顺其自然",
        "别犹豫了",
        "这件事值得",
        "先放一放吧",
        "你心里已有答案"
    },
    {
        "需求又要变了",
        "今天适合摸鱼",
        "加薪？想多了",
        "锅已在路上",
        "周五前会好的",
        "别问，问就对齐",
        "这个会可以不开",
        "先上线再说",
        "领导已读不回",
        "咖啡续命中",
        "文档先补上",
        "甩锅成功",
        "今天不加班",
        "评审又被打回",
        "年终奖稳了",
        "重启试试"
    },
    {
        "在我机器上是好的",
        "不是bug，是特性",
        "重启能解决九成",
        "祖传代码，勿动",
        "删库跑路预备",
        "null",
        "答案是42",
        "代码正在编译",
        "又双叒冲突了",
        "日志不会骗人",
        "先push备份",
        "这需求很简单",
        "跑通了就别碰",
        "堆栈里有真相",
        "周一再修",
        "false"
    }
};
