#!/usr/bin/env node
// 答案之书数据代码生成器: main/answers.json -> main/answer_data.h + main/answer_chars.txt
//
// answer_data.h   : 固件直接 #include 的答案字符串表 (UTF-8)
// answer_chars.txt: 答案/文案中出现的全部非 ASCII 字符, 供 lv_font_conv 生成中文子集字体
//                   (ASCII 可见字符由 lv_font_conv --range 0x20-0x7E 覆盖, 不进此文件)
//
// 用法: node tools/gen_answer_data.js
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const data = JSON.parse(fs.readFileSync(path.join(root, 'main/answers.json'), 'utf8'));

const decks = data.decks;
const perDeck = decks[0].answers.length;
if (!decks.every(d => d.answers.length === perDeck)) {
  throw new Error('每副牌条数必须一致');
}

// ---- 生成 answer_data.h ----
const esc = s => s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
let h = '// AUTO-GENERATED by tools/gen_answer_data.js from main/answers.json. Do not edit.\n';
h += '#pragma once\n\n';
h += `#define ANSWER_DECK_COUNT ${decks.length}\n`;
h += `#define ANSWERS_PER_DECK ${perDeck}\n\n`;
h += 'static const char * const ANSWER_DECK_NAMES[ANSWER_DECK_COUNT] = {\n';
h += decks.map(d => `    "${esc(d.name)}"`).join(',\n') + '\n};\n\n';
h += 'static const char * const ANSWERS[ANSWER_DECK_COUNT][ANSWERS_PER_DECK] = {\n';
h += decks.map(d =>
    '    {\n' + d.answers.map(a => `        "${esc(a)}"`).join(',\n') + '\n    }'
).join(',\n') + '\n};\n';
fs.writeFileSync(path.join(root, 'main/answer_data.h'), h);

// ---- 收集非 ASCII 字符 -> answer_chars.txt ----
const chars = new Set();
const collect = s => { for (const ch of s) if (ch.codePointAt(0) > 0x7E) chars.add(ch); };
collect(data.title);
for (const d of decks) { collect(d.name); d.answers.forEach(collect); }
const charStr = Array.from(chars).sort((a, b) => a.codePointAt(0) - b.codePointAt(0)).join('');
fs.writeFileSync(path.join(root, 'main/answer_chars.txt'), charStr + '\n');

console.log(`decks=${decks.length} perDeck=${perDeck} nonAsciiGlyphs=${chars.size}`);
console.log(`glyphs: ${charStr}`);
